//try catch
try{
    let a;
    //let a="pujaa";
    console.log(a.length);
    console.log("hi there from inside");
}catch(e){
    console.log("inside catch statement");
}


console.log("hii there")


